### ISSUE TITLE
Display more info in resignation letters

### ISSUE THREAD

**Issue by PwaPois** [binogure-studio/city-game-studio-i18n#178]
Around mid-game/end-game, you usually have multiple studios, and so when one of your employees resign, it becomes quite hard to find out in which studio they were and how skilled they were.

My suggestion is to display:
- The studio this employee was in (where the red line is)
- The design, development and polish capacities they had (where the blue line is) (to be able to easily find a proper replacement)

![image](https://user-images.githubusercontent.com/25114435/55899390-fa25a700-5bc4-11e9-873f-e2fe115b0795.png)

**Comment by xsellier** [comment]
Nice suggestion.

About the studio, I'm going to add it to the mail object. If there is a studio name it means the employee was in that studio, otherwise it means the employee was unassigned.

About employees capacities (design, development, polish), I will add something like that:

![image](https://user-images.githubusercontent.com/6616005/55902097-bf0d7e80-5b98-11e9-96cf-64184de22d9f.png)

**Comment by PwaPois** [comment]
Sounds good, thanks :heart:

**Comment by xsellier** [comment]
Closing, implemented in version v0.17.0
