### ISSUE TITLE
Suggestion multi release/ multi genre

### ISSUE THREAD

**Issue by JohnMann87** [binogure-studio/city-game-studio-i18n#202]
in the game it it looks like its ready for multi platform releases, like it looks designed for the player to choose more than one platform to release. why is it not a thing.  your game is the only one that doesn't allow this feature. (that sounds harsh didnt mean it harshly)

Also why did you make action adventure a separate genre wouldn't it be better for the player to choose both action and adventure. like I want my company to be known for RPG Open Worlds, but i cant. If you allow people to choose the different genres (combinations). it'll add for a hell of a lot more replay ability.  again like the multi platform issue it looks like its ready for the player to select multiple not just one.

Keep up the good work, even if you don't implement this. Its still a decently developing game.  looking forward to the new staff

**Comment by xsellier** [comment]
Hey,

Thank you for this suggestion.
The first part, releasing on several platforms at the same time has already been suggested. Let me link the issue here https://github.com/binogure-studio/city-game-studio-i18n/issues/159

About multi genre, there was another suggestion like this one (https://github.com/binogure-studio/city-game-studio-i18n/issues/115).

Thank you for those suggestions. I will keep this ticket open, for the multigenre. If enough people ask for it, I'm gonna implement it.

**Comment by xsellier** [comment]
Hey,

3 years later sorry. You can port games to several platforms at once, and you can wait before releasing a game. So the first point is implemented.

Regarding the second point, ie 2 genres for a theme, this ticket has been made lately: #151 and I'm gonna implement 2 genres for a 1 theme. So I'm gonna close this ticket, thank you for the suggestion tho!
