### ISSUE TITLE
Suggestion: Save Game Modification?

### ISSUE THREAD

**Issue by SHR2007** [binogure-studio/city-game-studio-i18n#204]
Hi,

First, I love your game.keep up the good work.

Second, I am an amateur cheater & was wondering If modifying a save game is possible at this point?
I have some ideas that I want to experiment with my employees.

So If you have the time,**would you kindly** tell me of way to modify the sats of my employees in the game?

Thank you.

**Comment by xsellier** [comment]
Hey,

Thank you for your kind words.
However modify the savegame is not allowed yet.
I can tell you I'm thinking about adding some cheat code to help players having the best stats for their game

**Comment by SHR2007** [comment]
OK,

Thank you for your response.
Yet,I will keep trying to find the stats.
Also,I could help you with the Arabic translation if you want.

Thank you

**Comment by Hisu0** [comment]
You won't find any stats as CGS is an encrypted format. I wouldn't presume to know why it's there, but as godot documentation says it's to prevent mobile users from getting stuff without paying, I assume there's something similar planned, maybe for the far future. I don't see what purpose would encryption serve otherwise.

**Comment by xsellier** [comment]
> You won't find any stats as CGS is an encrypted format. I wouldn't presume to know why it's there, but as godot documentation says it's to prevent mobile users from getting stuff without paying, I assume there's something similar planned, maybe for the far future. I don't see what purpose would encryption serve otherwise.

If the save file was in plain text many people would be modified it. But there is no deep validation yet. So, if someone has modified his/her save and it has modified its structure, it would crashes the game for sure. Since I'm the only developer of the game, I cannot afford spending time helping people fixing their savegame. So I took the decision to encrypt the savegame, just to save time.

Later, when I have time, I'm going to implement a deep validation of the savegame file, then you will be able to change them.

**Comment by xsellier** [comment]
Yo ucan directly cheat while playing without any credit cards. You just need to press F1 or F5, then type `help` to list the cheats.
Or if you want a lot of money: `currency set 99999999`

Closing it!
