### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by GeneralNW** [binogure-studio/city-game-studio-i18n#269]
Hey, I was just wondering if you had any plans to actually make a feature where we will have the ability to create our own video game console?

**Comment by xsellier** [comment]
About those suggestions, they are not on the official project roadmap yet.
I planned to released City Game Studio (ie out of Early Access) late 2020. So if I have spare time Im gonna implement those suggestions.  And, so far  Ican tell you, it should be part of the final release, but it won't implemented in 2019 (Im almost sure of that).

There is already another suggestion talking about that:
https://github.com/binogure-studio/city-game-studio-i18n/issues/226

Im gonna close this one because it is a duplicate.
