### ISSUE TITLE
Suggestion: Conventions affect games?

### ISSUE THREAD

**Issue by ClassicBiz** [binogure-studio/city-game-studio-i18n#330]
Conventions should have more of an impact on the hype of games you haven't yet released.
To have an unpublished game shown at the convention would increase its hype or start hype for it.
To put a game out early in a convention could lead to a bad hype score.

Personally Conventions seem good at giving you little boosts in sales but I feel like it can offer more.
 1. It can effect your hype score. Say you select a big game to go in a indie convention it would go 
down or it wouldn't be as effective in giving hype as if you were to select that game for a big convention.

2. Displaying your games to early. It states it self, but basically if you were to select a game that would be early in development for a convention it could hurt the games overall hype when released.

3. Having it boost your games hype! SO lets say you have a game that just needs a little push in hype and a convention happens. You select this game for the convention and it goes up in hype making the game more of a hit!

4. There can be pros and cons. The Pros of doing this would be hype is now affected in more than one way. I feel conventions could be more interactive. 
 The Cons of having hype being affected by conventions is personal conventions. you could line up one after another. At the same time I'm not sure how good this would be for exploiting.
Personal conventions could be limited or it could just barely affect a game's hype.

**Comment by xsellier** [comment]
You are right about that. In fact, a convention affects the hype of the game. But there are 2 types of hype.

![image](https://user-images.githubusercontent.com/6616005/70070379-7f7d2200-15c1-11ea-9c33-c79fa6b7a60e.png)
The dynamic hype is computed when you market your game. It applies a boost ratio. Meaning if you have a boost ratio of 1.8 and you've made 1000 sales, you will sell 1800 copies.

The static hype is computed when you attend a convention. This one is hidden because it was designed for released games only. I've added it to the non-released games but I forgot to show it.
It applies a static boost for sales. Meaning, attending a convention might lead to increase your sales by 500 copies (for example).

About personal conventions, the more you do the less it impacts your games.

**Comment by xsellier** [comment]
Should be part of https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-18020128

**Comment by xsellier** [comment]
Convention have been reworked with v1.0.0. Closing this ticket
