### ISSUE TITLE
Bug: Cannot get games in Game of the year top

### ISSUE THREAD

**Issue by SkipTheDragon** [binogure-studio/city-game-studio-i18n#359]
**Describe the bug**
^^ Title

**To Reproduce**
1. Create game with high score points(my highest was 94)
2. Submit it for game of the year
3. You do not appear on the top 3

**Expected behavior**
Get at least 3rd place. (i played for 5 hours today, started the save from scratch yesterday)

**Logs**
Attach log files to this ticket:
(I didn't know what to upload so i uploaded my full appdata game folder) Removed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v0.28.2

**Comment by xsellier** [comment]
I can confirm that you got a solid 94%, however the GOTY edition score computation is a bit more complicated that just the score.

This is a rough formula:
```
game_score * game_size_ratio * clamp(theme_trend_ratio, 0.9, 1.1)
```

The game size ratio depends on the difficulty, since you are playing on normal, you've got:
```
94 * 1.0 * 0.9 = 84.6
```
That is really unfortunate, because the theme was not trending at all at the time, but getting a GOTY edition of a game has to be difficult.
