### ISSUE TITLE
Outsourcing

### ISSUE THREAD

**Issue by IkhwanKS3** [binogure-studio/city-game-studio-i18n#362]
Sometimes when you want to do a game with new genre you just discover you don't know the best slider setting, so maybe you can outsourcing either design/development/polish to other companies that are more expertise in that to get a better score. The report will give more tips than than normal because of course the outsourcing companies already know the best slider setting. The price to pay can be either in a form of royalty or one time pay.

**Comment by xsellier** [comment]
I get the point. Making games with new genres it is quite challenging. Finding the good ratios, still making money... but if you make contracts instead of making games, you will obtain the same result.

Also, you can publish game offers, so your competitors are going to make games for you.

What will this feature bring, that is not already in the game?

**Comment by xsellier** [comment]
Since this issue doesn't fit the issue template, nor explains how or why it enhance the gameplay, I'm closing it.
