### ISSUE TITLE
Suggestion: Studio automation

### ISSUE THREAD

**Issue by JRC86** [binogure-studio/city-game-studio-i18n#365]
I'd like to have one of my studios to continuously do contract work unless I specifically pick them a task.
The way it could work is that when picking a contract to have a checkbox that makes that studio continuously work on contracts. 
A different approach would be the studie overview page.

**Comment by xsellier** [comment]
I'm working on this by adding joint studio projects. So instead of having 50 studios working on 50 differents stuff, you will be able to make one big project using all of your studios.
For example, I'm going to change how many employees are required to make a AAA, it is going to be 250 employees for a AAA game.
- 1 employee for an indie game
- 3 employees for a normal game
- 50 employees for a big game
- 250 employees for a AAA game

This update, should be part of v0.29.0

**Comment by icls1337** [comment]
cool

**Comment by xsellier** [comment]
So the v0.29.0 is now out, and this issue is duplicated with this one:
https://github.com/binogure-studio/city-game-studio-i18n/issues/409

So Im closing this one.

**Comment by proxyspride** [comment]
I think what he is saying is that it would be convenient if we could basically set a team to continuously do contracts until we tell them to stop, if they could be set as autonomous contractors until instructed otherwise?
