### ISSUE TITLE
Suggestion: Custom platforms

### ISSUE THREAD

**Issue by Th-byte** [binogure-studio/city-game-studio-i18n#403]
1. The game platform is divided into two parts: home game machine and hand-held game machine
2. Platform development content: processor (2 cores, 4 cores, 8 cores, 16 cores, 32 cores, 64 cores), CPU (first generation graphics engine, second generation graphics engine, third generation graphics engine, fourth generation graphics engine, fifth generation graphics engine), memory (2G, 4G, 8g, 16g, 32g, 64g), hard disk (200g, 250g, 500g, 1TB, 2TB), handle (wired game handle, wireless game handle ）Wired game controller: (first generation, second generation, third generation, fourth generation, fifth generation) wireless game controller: (first generation, second generation, third generation, fourth generation, fifth generation), shape (color, other shapes)
3. Cracking platform: the higher the platform configuration, the longer the cracking time. The release time of firmware varies according to the configuration level. Releasing firmware can reduce the loss of platform cracking.
4. Platform R&D mechanism: in terms of configuration, R & D cost is from low to high, and R & D time is from low to high. The difficulty of game development is also related to the level of configuration.
5. platform authorization: the authorization is divided into two parts: computer player authorization (25%) and host unit price. The license fee affects the sales volume of the host.
6. Platform interface: display platform sales, player desire index and game sales. Number
7. CD Type: cd-p, CD-R, CD pro

**Comment by xsellier** [comment]
Sorry to say that, but thoses suggestions are out of the scope for [v0.31.0](https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-27080508).

The [v0.31.0](https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-27080508) will contain:
- Platform exclusivity
- Developping games for upcoming platforms
- Grey out already ported platforms to the platform list
- Multi-game ports

For custom platforms, it would be better if you can add a comment to [this ticket](https://github.com/binogure-studio/city-game-studio-i18n/issues/311) instead of opening a new one.

**Comment by xsellier** [comment]
If this feature is implemented it will also contains platform exclusivity where you can force your competitor to publish games only on your platforms.

**Comment by xsellier** [comment]
Custom platforms have been implemented.
