### ISSUE TITLE
Suggestion: Some new Suggestions

### ISSUE THREAD

**Issue by hyi1233** [binogure-studio/city-game-studio-i18n#418]
1. 关于游戏开发，是否添加手机游戏制作模块，手机游戏app商城类！建议添加DIY游戏封面。
2.关于游戏硬件开发，每一个游戏制作公司都是最了解游戏硬件的工程师，想要体现游戏的真实性，可玩性，流畅性，画质等，大公司都有能力去开发体现自己游戏的硬件设备！建议后期加入硬件开发，制作自己的游戏设备！开发后的硬件，也可以授权给其他公司等等！
3.关于员工，建议调整员工等级，初级，中级，高级，每个等级的员工，所会的技能有所不同，高级全面技能，如:画质，3D，编程等等！每个技能对游戏的开发有加成效果。而员工的招聘可以从，社会人，学校，猎头等渠道招聘。而想要猎头或者挖取别人公司员工，除了工作高薪以外，还需要特定的条件，比如:公司名气、游戏排名，工作场地，硬件，福利等等！
4.关于AI公司:除了开局选定的AI公司，系统应该自动生成其他独立工作室，独立工作室，是私人公司，有的开发游戏，有的开发硬件等等，按一定条件，可以收购独立公司，收购后可以使用独立公司持有的专利，其他AI公司如果使用，必须申请授权，当然AI也可以收购独立公司，玩家需要申请授权给授权费！另外:游戏中如果AI公司被收购后，系统也要在特定时间，自动生产AI公司，保持玩家游戏选择的AI公司数量不减少！玩家和AI公司上市后，还可以成立独立公司，独立公司达到上市条件也可以上市！
5.关于股市及收购:结合以上，不管是AI公司，还是玩家公司，都持有股票机制，达到条件可以上市。而玩家，或者AI都可以通过股市购买股票，当然收购也是可以通过购买股票持有数收购上市公司！没有上市也可以通过购买收购。上市后的公司也可以成立分公司，或者独立公司等等！
6.关于商城:建议添加商城功能，可分为线上与线下，当然线上现在已经存在，线下可以成立商城，游戏实体销售店！实体店可以在地图修建，也可以租用，主要可以销售游戏(玩家公司，AI公司)，以及硬件设备，游戏周边等等！当然玩家可以成立商城（线上线下），AI也可以成立，独立公司也可以成立，也可以被收购，打压，破坏等等！
7.关于游戏周边:当游戏销量，或者获得年度版后，游戏可以授权周边，如:玩具，电影改编等等！
8.关于福利:在人力支援管理，添加员工福利，如:养老保险，医疗保险，旅游补贴，就餐补贴，生育津贴，股权划分(员工被挖走后股权也跟随)等等！来提高员工待遇及忠诚度！每个工作室游戏销量达到目标，可以选择旅游，旅游地点玩家可以选择！
9. 关于画质，建议添加支持16:9显示器全屏！
10.关于地图：建议增加银行、商店、游戏实体店、游戏周边、旅游大地图等
11.服务器：建议在地图增加服务器商店，可以收购或者入股云服务器！

以上是中文！
The following is an English translation
1. About the game development, whether to add the mobile game production module, mobile game app mall class!Suggest adding DIY game cover.
2. As for the development of game hardware, every game production company is the engineer who knows the game hardware best. In order to reflect the authenticity, playability, fluency and picture quality of the game, large companies have the ability to develop hardware devices that reflect their own games!Suggest later join hardware development, production of their own game equipment!After the development of the hardware, can also be licensed to other companies and so on!
3. As for the staff, it is suggested to adjust the staff level, namely, junior, intermediate and advanced. For each level, the staff will have different skills.Each skill adds to the development of the game.The recruitment of employees can be from social, school, headhunter and other channels recruitment.To be a headhunter or poach an employee from another company, you need certain requirements besides high salary, such as company reputation, game ranking, working place, hardware, benefits and so on!
4. About the AI: in addition to start the selected AI company, the system should automatically generate other independent studios, independent studio, is a private company, some games, some development hardware and so on, according to certain conditions, can be an independent company, after buying can use independent company held patents, if you use other AI company, must apply for authorization, AI, of course, can also be an independent company, players need to apply for authorization to licensing fees!In addition, if the AI company is acquired in the game, the system should also automatically produce AI companies at a certain time, so as to keep the number of AI companies selected by the game unchanged.After the players and AI companies are listed, they can also set up independent companies, independent companies can also be listed to meet the listing conditions!
5. About the stock market and acquisition: combined with the above, no matter the AI company or the player company, they all hold the stock mechanism and can be listed upon the condition.And the player, or AI can be through the stock market to buy stocks, of course, the acquisition is also through the purchase of shares held by the number of acquisition of listed companies!Not going public can also be bought through acquisitions.After listing the company can also set up a branch, or independent companies and so on!
6. About mall: it is suggested to add mall functions, which can be divided into online and offline. Of course, online already exists, offline can be set up mall, game entity sales store!Physical stores can be built on the map, can also rent, mainly can sell games (players companies, AI companies), as well as hardware equipment, game peripheral and so on!Of course, players can set up a mall (online and offline), AI can be set up, independent companies can be set up, can also be acquired, suppress, destroy and so on!
7. About peripherals: when the game sells, or gets the annual edition, the game can authorize peripherals, such as: toys, movie adaptations and so on!
8. About benefits: in the human support management, add employee benefits, such as: pension insurance, medical insurance, travel subsidies, meal subsidies, maternity allowance, equity division (after the employee is poached the equity also follows) and so on!To improve employee treatment and loyalty!Each studio game sales to achieve the target, can choose to travel, travel site players can choose!
9. Regarding picture quality, it is recommended to add support for 16:9 full screen monitor!
10. About maps: it is suggested to add Banks, stores, game stores, game perimeters and tourism maps
11. Server: it is recommended to add a server store in the map, which can be acquired or become a shareholder in the cloud server!

**Comment by icls1337** [comment]
cool

**Comment by xsellier** [comment]
Hello,

Thank you for all the suggestions.

1. Mobile platform: Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/410
    DIY game cover: This will increase the savegame size like crazy, so I think adding a description field for the game you are creating is better: https://github.com/binogure-studio/city-game-studio-i18n/issues/400
2. Duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/426
3. This suggestion is huge, it is partially covered by those tickets https://github.com/binogure-studio/city-game-studio-i18n/issues/214 and https://github.com/binogure-studio/city-game-studio-i18n/issues/199
4. Duplicated from those tickets: https://github.com/binogure-studio/city-game-studio-i18n/issues/413 and https://github.com/binogure-studio/city-game-studio-i18n/issues/407 and https://github.com/binogure-studio/city-game-studio-i18n/issues/340
5. Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/77
6. It is a great suggestion, however I'm not going to add physical store, because it is off topic. You are a video game company, not a video game store company.
7. Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/198
8. Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/199
9. 16:9 full screen monitor is already supported, maybe you are talking about another resolution?
10. Bank, stores, game stores and tourism are off topic. Upcoming buildings are universities to train your employees. Their is a ticket about map extends already: https://github.com/binogure-studio/city-game-studio-i18n/issues/326
11. You can already build/buy studios and furnish them with servers automatically, why do you want to buy servers room from the city map?
