### ISSUE TITLE
Suggestion: Make the pop-up notification icon appear instantly rather than to hit the edge of the screen and bounce back like in the current build

### ISSUE THREAD

**Issue by PLord84** [binogure-studio/city-game-studio-i18n#525]
Pretty much the title,
Make the pop-up notification icon appear instantly rather than to hit the edge of the screen and bounce back like in the current build.
Why? personaly i think it's kind off annoying to try to open the pop-up fast but it bounces back and you have to "catch" the pop-up, it's an "neat" visual effect but practicaly just makes me want to toggle off most notifications (Which is a great feature, and thanks for implementing it!)

**Comment by xsellier** [comment]
Hey,

Thank you for that feedback, do you mind trying out the unstable Steam Branch (Right click on City Game Studio => Properties => Betas => Select Unstable). Because I implemented this suggestion:
https://github.com/binogure-studio/city-game-studio-i18n/issues/523

Most important suggestions are going to be shown as a popup

**Comment by proxyspride** [comment]
This is still not fixed in the current unstable branch, the pop-ups still take a moment to bounce on the edge of the screen, making me wait to click it until it's done bouncing. I think there was some miscommunication here. :P

**Comment by xsellier** [comment]
Should be part of the next update! You can already try it by switching to the unstable steam branch,

Right click on City Game Studio, select properties, then Betas and click on Unstable.
