### ISSUE TITLE
Console Suggestions

### ISSUE THREAD

**Issue by DeadlyDragoon** [binogure-studio/city-game-studio-i18n#540]
I messed around with the latest update and I feel the console creation aspect could use a few updates. Here are my suggestions to spice them up!
- Games have fans. You can gain fans through games. Why can you not gain fans through consoles? I made 7 million dollars worth of profit off of selling my console but I gained 0 fans. Shouldn't people be a fan of the console?
- Options! The components that go into making a console, early on at least, are limited. Even in the early console days you'd have a lot of different options for the hardware. Seeing more choices would be cool. Perhaps a mod could fix this though?
- Games for the console! I want to view the list of games people have made for my console and their score. I know the game tells you how many total games have been made for the console, but you have no way to view what games those are specifically.
- Marketing... I have no way to market my console early on. Why?
- Target Audience / Genre Audience... The player should have control over what genres and what themes and what target audiences work well for the console. This should tie into marketing in some way. If you market the console for adults, then M rated games should be more popular. The same should be done for genres / themes.
- Controllers? What effect do they have on the console? Knowing this would be nice! Having more options as well. You have zero controller options in 1981. Consoles in that year did have controllers.
- Money! I blindly made a console with 49% quality. I had three launch day titles that were rated 62%, 55%, and 33%. I had 45 fans. I ended up making 7 million dollars worth of profit after 3 years, with having released 11 total games of average quality. I was playing on the normal difficulty and was able to make profit without even trying. SOOO many companies went bankrupt early on due to their consoles, especially in the early years. Yet here I am with 45 fans and a dozen crappy games making bank!
- Licenses. I want to charge developers for making games on my console. Nintendo made me pay 1.3 million for a NES license after all.
- Console Reviews. Consoles get reviewed upon release in the real world. 

Hopefully you can add some more to the console aspect of the game! I know it's not the main focus of the game with it being called City /Game/ Studio afterall. Regardless, It'd be nice for some more complexity with it.

**Comment by xsellier** [comment]
Thank you for that report.

1. Fan made by consoles. A console is great as soon as it has great title on it. So it is pretty mich the games that make you a console fan.
2. Mod support are coming in the next update. So you should be able to add more component to the custom platforms
3. Indeed a good idea!
4. You market your console by making games for it. So As soon as you market a game and it is published only on your console it will also market your console.
5. Those are computed regarding the console type and also your company's profile. So if youmake only action games, your console will be specialized for action games, because you know how to do them
6. It is a bug, and Im gonna fix it.
7. It depends on the difficulty you are playing. I mean if you are playing in the first difficulties hen it is normal, because I want people to enjoy the game without much trouble making money. But if you played using the hardests difficulties, then please update this ticket and tell me how you dou it, because I want to know your secret :-)
8. I though about that one, and I think I'm gonna add it, but remember you want people to make games for your console, unless you are Nintendo and you have a 50% market share console.

**Comment by xsellier** [comment]
Point 6 has been fixed on the unstable Steam branch.

**Comment by xsellier** [comment]
Hey,

You can now mods consoles, adding new console parts, which is great! There's a ton of mods on the steam workshop for it!
 This one is the best one so far https://steamcommunity.com/sharedfiles/filedetails/?id=2804483837
You can also list all the game made for your consoles, yo ucan pay competitors to make games for your console, so it is a way to market them.

Most of the suggestions you've made have been implemented. For the rest, if you want them in City Game Studio, I invite you to create one ticket per suggestion.

Cheers
