### ISSUE TITLE
Suggestion: Developed game - no release, just report for better developing

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#555]
When player develop a game in new genre, he doesn't know correct sliders

**Describe the solution you'd like**
After game developed fully (window of price) reject a developing (reject a publish in fact, game is developed) and create report for better sliders understanding

**Additional context**
This is good feature for rich developer who cares own reputation. Because indie dev has no money to reject fully developed product.

Note - block of 100% knowledge of sliders, because it could be opportunity to create indie games and reject them until knowledge will be perfect. 

I dont know mechanics of CGS perfectly, so probably this is bad suggestion.
In other hand, mb my idea will evolve in something good in your head ;)

Cheers

**Comment by xsellier** [comment]
Hey,

Not releasing a game has to have a bad impact on the studio. Generally there is no post-mortem on canceled games, because there was no production, so no customer feedbacks. But it is a video game so we can make it happen.

However, there is another feature that exists which is Contracts. Completing a contract trains your staff and also give you tips like a post-mortem. But you also get some money.

Also, regarding canceling a game, when should we be able to do a post-mortem? Once it is almost ready to be released, or during the polish step, or during the development step? Implementing such thing is easy to do, so why not. But you will have to trigger the post-mortem manually.
