### ISSUE TITLE
Suggestion: Mortgage Menu Enhancement

### ISSUE THREAD

**Issue by ThisNekoGuy** [binogure-studio/city-game-studio-i18n#562]
**Is your feature request related to a problem? Please describe.**
I have a few problems in regards to the Mortgage Menu and they are quite severe.
(This may be connected to my other suggestion recently about using company assets to liquidate debt, but this is a little more direct on the topic of the menu as a whole.)

1. When the player suddenly incurs a huge amount of debt, the performance of the game drops hard with each *new* Mortgage window that opens; it can get to a point where one can literally wait between 10-30 seconds for the next one appears because there's so many
2. I'm not trying to say "make the game easier," as I know there has to be a clear lose condition, but semi-truck dumping dozen batches of payment plans at a time and multiple times a month does make sense realistically but it's hell on the player (Perhaps organize them?)
3. If the player is literally on the verge of finishing a new game, maybe striking a deal with an NPC at the bank would be a great idea; this is one of my worst experiences with the menu besides the performance and presentation. It's not too hard to imagine such a deal being made if the product will pay a TON down on the debt but I'd imagine that such a mechanic may need to be balanced. I love the game to death, but it's really difficult for the experience if loss is such a razor-sharp edge

**Describe the solution you'd like**

1. Optimizing the Mortgage window presentation; it slows down the game significantly
2. Perhaps make the Mortgage menu less spam-y?
3. Smooth out the edge between survival and instant-loss

**Describe alternatives you've considered**
Issue https://github.com/binogure-studio/city-game-studio-i18n/issues/558 covers my other ideas in assisting with this; but you already know that

**Additional context**
![20210321235705_1](https://user-images.githubusercontent.com/28468662/111942394-1a598280-8acb-11eb-94aa-a4a7f545097e.jpg)
![20210322000355_1](https://user-images.githubusercontent.com/28468662/111942823-111ce580-8acc-11eb-9b0c-3893ec24420d.jpg)

There's just got to be a better solution than this... especially on the 2nd easiest difficulty :skull_and_crossbones: 
Like, it's one thing to be too easy, I don't want "Normal mode" to be easy but this is unmanageably out of hand; once you're in it, you're stuck in it

**Comment by xsellier** [comment]
Gotcha

**Comment by xsellier** [comment]
Awesome suggestion.
So what I plan to do if you lose more than 10% of your currency within 3 months (or more than 1 million $), it is going to slow down the game and displays a tooltip explaining you are losing money. The tooltip will have a checkbox saying: `Don't show it again` so it will disable that message forever and stop slowing down the game.

If you are close to bankruptcy, let's say you have less than 10k $, then the game will automatically shows the mortgage panel suggesting you to get one.

Also, regarding your other issue, I think it would be better to force a minimum mortgage value, because having 50x mortgages at the same time is not a good idea. It is better to have only one, but a big one. Then you invest and start making money.

Thank you for your suggestion!

**Comment by ThisNekoGuy** [comment]
Thanks, I appreciate it 👍 

It's just really hard to not get instantly bankrupt when you've got servers to host, 5 or more studios, and you're trying to get a game out the door while the "Huge" category drains millions upon millions with no method available to mitigate it thus sinking my company to the bank faster than the Titanic

**Comment by xsellier** [comment]
Thank you for that report. I fixed it on the unstable Steam branch already!
