### ISSUE TITLE
CGS in android/Ios?

### ISSUE THREAD

**Issue by GGplays** [binogure-studio/city-game-studio-i18n#604]
CGS in android? I ask because Godot Have support to android (i think) and i want to play my favorite simulation game while pooping

**Comment by xsellier** [comment]
Hey,

Indeed Godot Engine supports Android and iOS. I dont have any plan to support any of them atm because it woud require too much work to rework all the controls, and to unplug steam from the game.

However, since you can remote play together with Steam, I plan to fully support that feature, so you will be able to play on your mobile device thanks to steam!
