### ISSUE TITLE
Suggestion: Features for own consoles

### ISSUE THREAD

**Issue by Zebbidoo** [binogure-studio/city-game-studio-i18n#612]
Making your own consoles is great! It is a great feature, but there are a couple of things I would like to suggest, as I feel they would make distributing your own consoles better.

First, it would be great if you could bundle a game with your consoles, thus helping to spread that game and hopefully gain fans.

Secondly, I find that occasionally I sell my own console in many thousands, but the one or two games I have published for it only sell a couple of hundred copies. In reality, you would buy at least one game for a console, else why buy it? So maybe there should be a bonus to game sales for the consoles to at least make each sold console equate to one sold game. For example. If I have sold 100k consoles, and the console has, say 5 games, those games could have a bonus to sales that gets smaller the more games the console has. So basically a bonus calculated from game library vs sold consoles.

Thirdly, it would be great if I could negotiate publishing rights for my console with others who want to publish for them. Like you have to do for Grantendo for example.

Those are all my suggestions. Thank you for a great game so far!

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestions.
Regarding point 1, it's already been suggested: https://github.com/binogure-studio/city-game-studio-i18n/issues/421
About point 3, it's already been suggested: https://github.com/binogure-studio/city-game-studio-i18n/issues/603

Regarding point 2, it is all about the number of unit sold. If you've sold only few thousand of consoles, you cannot expect to make a profitable AAA. You'd better target 1 million unit sold before making a AAA for your console. To reach that point, I suggest you to run a marketing campaign with at least 10 millions $ per month and to assign a good marketing manager (over 50% boost). After that, lower the price of your console and run a sale (just a 20% sales for 3 months for example). Or you can publish something like100 games on your console. Or you can publish 10 games, and run a 1 million $ marketing campaign, it is up to you, it is adjustable.

I'm closing this topic since it's been already suggested or implemented.
Regards
