### ISSUE TITLE
Suggestion: Game development during process of creating a console

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#628]
We can buy license of a platform and start to develop a game before console released.
This is cool feature, and strange, that it's no able to create games for OWN console in the same way.
Is it possible to improve this?

Cheers!

**Comment by xsellier** [comment]
You can already do this. Since you can start making games before you release your console.
When you get an announcement for a console, it means it is ready to be released but there is no ame available on it yet. So you can start making game for that platform.

You can do the same for your own console, once ready don't release it immediatly, just hold, and make games. Then yo ucan release everything at once.
