### ISSUE TITLE
Suggestion: License for traditional publishing? 

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#633]
Do we need to buy license for traditional publishing? 
A game is not us, it's just a contract for developer, so competitor must have license?

**Comment by xsellier** [comment]
Hey,

When you need to make a game for a console you dont' own, you better buy it. That's why you get money to develop the game.

> Do we need to buy license for traditional publishing?
Yes you need to buy license of the platform for traditional publishing. On the bright side, they offer you money to do so.

> A game is not us, it's just a contract for developer, so competitor must have license?
The competitor doesn't need to own a license, but by default it does own it, made it happen anyway.
