### ISSUE TITLE
Suggestion: Ultrawide Support/Stretch

### ISSUE THREAD

**Issue by Ayumix3** [binogure-studio/city-game-studio-i18n#646]
I saw in the Steam discussions that support for Ultrawide resolutions is limited/not doable cause of the Engine(Godot 2.1?).

Would it be possible to at least add stretching from 19:9 aspect ratio to 21:9 aspect ratio? 

While of course full support would be better, having at least some options to remove the black bars on the sides would be nice.

**Alternativly:** Add an option to make the game "true" fullscreen, since it seems to be running in borderless fullscreen when selecting the fullscreen option. This would probably enable Cropping/Stretching options via 3rd party software (Nvidia and AMD both offer GPU scaling and resizing options for screens.)

**Comment by xsellier** [comment]
Hey,

Thank you for the suggestion, I'm gonna take some time to explain what's happening and why it cannot be done.

First, you are right I'm using godot Engine 21, and with Godot Engine 2.1 you can define one resolution, then make scale, ie keep the same ratio ( https://docs.godotengine.org/en/2.1/learning/features/viewports/multiple_resolutions.html ) . There is no proper fullscreen option, even in the latest option of Godot Engine.

Let me explain few stuff about the 3 options from the doc:
- Disabled: No scaling at all, if it is defined for 1600x900, then no matter what it will stay in that reslution
- 2D: This is the best multiple-resolution support here, but you canno change the ratio.
- Viewport: You can change the ratio but, everything is gonna get really pixelated and blurry, and quite ugly. So that's not an option.

There is another aspect that I can try:
Stretch aspect **Keep Width**, I'm gonna try to make it work in the coming week, but I cannot promise anything.

**Comment by xsellier** [comment]
So far, that's the result I got:
![image](https://user-images.githubusercontent.com/6616005/170940572-0876f9de-075c-489d-ab9b-d0646beeb621.png)

I still have some work to make it work:
![image](https://user-images.githubusercontent.com/6616005/170940680-ae54a679-5942-4902-a2b7-364e1a650443.png)

The UI has changed quite a bit since it is the very next update.

**Comment by xsellier** [comment]
Still have some work to do (mini games) and a full test then I'll deliver to the default Steam branch:
![image](https://user-images.githubusercontent.com/6616005/170975349-97bc0639-ee6d-4c18-bcf4-f542eff78ed2.png)

**Comment by xsellier** [comment]
So, I've been working on this feature and I have a good news, it is now available on the steam unstable bracnch since v1.8.0-rc5.

feel free to try it out.
Meanwhile I'm closing this issue, it should be available on the default branch by 3rd of June 2022.
