### ISSUE TITLE
2 Suggestions

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#700]
First: cant customize the colour of a case added by mods
Second: can make money with the university opening it to public, you cant train your employees but you generate some money

**Comment by xsellier** [comment]
Hey, thank you for the suggestion.

Usually it is one suggestion per issue.
For the first suggestion, it's already been suggested (duplicated):
https://github.com/binogure-studio/city-game-studio-i18n/issues/650

For the second one, it won't be implemented since making money from university is the not the main goal of managing a video game company (off-topic).
