### ISSUE TITLE
Suggestion: Add Arabic Translation

### ISSUE THREAD

**Issue by PowerX-NF** [binogure-studio/city-game-studio-i18n#720]
please add arabic translation you will find it here

https://github.com/PowerX-NF/city-game-studio-i18n/blob/master/languages/ar.yml

**Comment by xsellier** [comment]
Hey,

Since the game engine doesn't support RTL languages, I cannot add arabic translations to City Game Studio.
I;m using godot Engine v2.1. I already looked to add arabic translations in the past, and it would take something like a month to implement, and with a ton of tweaks and workaround for a poor result.

However, if you are willing to add arabic manually, it is doable via the mod-manager:
https://modmanager.city-game-studio.com
