### ISSUE TITLE
Suggestion: Own Console Case

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#729]
Can make the case of the Custom Platform like the logo of the company

**Comment by xsellier** [comment]
You can do it via mods already.

**Comment by GianluPlay** [comment]
> You can do it via mods already.

Yes but isnt the same, this feature would be in the base game

**Comment by FoaxZed** [comment]
I think what he means is, it is something you can make a mod, so there is no need to put it in the base game. You can already do it, you just have to do it yourself.

**Comment by xsellier** [comment]
Since it is doable via mods, I won't push it to the game itself.
If  you want to add a new console case, then yo ucan create a new mod to add one, then load it to your sawegame. What's cool about it, is you can even share it via the Steam workshop, and be the cool kid making new console cases.

I'm gonna close this ticket since there is a viable alternative to do it.
