### ISSUE TITLE
Suggestion: Add/remove studio while making a game

### ISSUE THREAD

**Issue by Lioncandy08** [binogure-studio/city-game-studio-i18n#736]
Every time a studios is doing an action/working on it, you can't add/remove any studios on the project. Can you implement the option to add/remove studios during the working phases?

**Comment by xsellier** [comment]
Hey,

You can add/remove a studio from a project while it is in development since the v1.4.0.
Sometimes a studios can be stuck on a project for a week (or two). I suggest you to resume the game wait for a week and you should be able to add/remove studios (see update https://steamcommunity.com/app/726840/eventcomments/3043859446181481591 )

**Comment by xsellier** [comment]
Implemented in v1.4.0
