### ISSUE TITLE
Suggestion: Game Testing Department and Bugs

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#751]
Function: Fix Bugs, Add Polish Points

Cost:
Fix Bugs Free (salaries are not included)
Polish Points 25.000 Per Month (Salaries are not included)

**Comment by xsellier** [comment]
Hey,

* Does this feature request related to a specific problem?
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

* Please describe all the alternatives you've considered for that specific problem.

Side note:
You may have noticed that I don't always reply to your suggestions. I'm sorry because I should have told you that I'd rather take my time to answer to suggestions that use the Feature requst template than just a bunch of words that barely describes a new feature.

So, if you want me to reply to all of your suggestions, you may want to start by using the feature request template.

**Comment by xsellier** [comment]
Since this issue doesn't fit the issue template, nor explains how or why it enhance the gameplay, I'm closing it.
