### ISSUE TITLE
Marketing panel, add gameports to the charts

### ISSUE THREAD

**Issue by xsellier** [binogure-studio/city-game-studio-i18n#79]
Marketing panel, add gameports to the charts

**Comment by RedditCaptain** [comment]
Maybe ports should fall under the original title when it comes to marketing? (if that isn't already the case in the background?) 

I know the marketing drops when the original game gets taken of the market even when there are still ports selling, but because sometimes I'm running like 10+ ports of my games and having them all separately for marketing would make the menu very messy quickly.

So the title will remain in the marketing tab for as long as ports are running instead of having ports separately on the list?

**Comment by xsellier** [comment]
Gameports have been added to the marketing charts.
